wechaty/go-wechaty

- .gitignore
- README.md
- examples/bot.go
- src/wechaty/wechaty.go
- add `wechaty.go` fake code
- add `examples/bot.go`
- update todo plan
- add `.idea/` to `.gitignore`
> update golang examples

- README.md
Signed-off-by: dchaofei <dchaofei@163.com>
> update README.md image.py => image.go

- src/wechaty-puppet/schemas/message.go
Sorry, my push slower.
Signed-off-by: dingdayu <614422099@qq.com>
> go fmt message.go & update Timestamp types of int to uint64

- wechaty-puppet/memory-card/memory_card.go
- wechaty-puppet/memory-card/memory_card_test.go
- wechaty-puppet/memory-card/storage/backend.go
- wechaty-puppet/memory-card/storage/file.go
- wechaty-puppet/memory-card/storage/file_test.go
- wechaty-puppet/memory-card/storage/nop.go
- wechaty-puppet/memory-card/storage/testdata/.gitignore
- wechaty-puppet/memory-card/testdata/.gitignore
The simple implementation of memory-card can not be as complicated as the TS version at present. The goal is to run the go wechaty demo first, and then iterate as needed later.
Question 1: which directory is suitable for such a toolkit?
> Add memory_card

- wechaty-puppet/events/events.go
- wechaty/wechaty.go
> add new events emitter

- examples/ding-dong-bot.go
- wechaty-puppet-hostie/puppet_hostie.go
- wechaty-puppet-mock/puppet_mock.go
- wechaty-puppet/option.go
- wechaty-puppet/option/option.go
- wechaty-puppet/puppet.go
- wechaty/interface/accessory.go
- wechaty/option.go
- wechaty/user/room_invitation.go
- wechaty/wechaty.go
see https://github.com/wechaty/go-wechaty/issues/11
> puppet abstract class

- .github/workflows/codeclimate.yml
> Fix .github./workflows/codeclimate.yml

- .github/workflows/pr.yml
Replace `sladyn98/auto-go-format` to `dingdayu/auto-go-format`
> Update Go Formatter

- README.md
- wechaty-puppet/puppet.go
- wechaty-puppet/schemas/events.go
- wechaty/event.go
- wechaty/factory/room_invitation.go
- wechaty/factory/tag.go
- wechaty/factory/url_link.go
- wechaty/interface/room_invitation.go
- wechaty/interface/tag.go
- wechaty/interface/url_link.go
- wechaty/user/message.go
- wechaty/user/room_invitation.go
- wechaty/user/tag.go
- wechaty/user/url_link.go
- wechaty/wechaty.go
> Improve wechaty user

- README.md
- wechaty/accessory.go
- wechaty/factory/contact.go
- wechaty/factory/friendship.go
- wechaty/factory/image.go
- wechaty/factory/message.go
- wechaty/factory/room.go
- wechaty/factory/room_invitation.go
- wechaty/factory/tag.go
- wechaty/interface/accessory.go
- wechaty/interface/wechaty.go
- wechaty/user/contact.go
- wechaty/user/contact_self.go
- wechaty/user/friendship.go
- wechaty/user/image.go
- wechaty/user/message.go
- wechaty/user/room.go
- wechaty/user/room_invitation.go
- wechaty/user/tag.go
- wechaty/wechaty.go
i found that all interfaces have been named `IName` expect `Accessory`, so i renamed it.
> style: rename interface `Accessory` to `IAccessory`

- CONTRIBUTING.md
Update Nomination URL and Go install URL
> Update URL of CONTRIBUTING.md

- go.mod
- wechaty-puppet-hostie/puppet_hostie.go
- wechaty-puppet/puppet.go
- wechaty-puppet/schemas/payload.go
- wechaty/user/contact.go
- wechaty/user/message.go
- wechaty/user/room.go
- wechaty/wechaty.go
add DirtyPayload.
add send miniprogram
> add DirtyPayload

- wechaty-puppet-service/puppet_service.go
- wechaty-puppet/file-box/file_box.go
- wechaty-puppet/file-box/file_box_stream.go
> fix sendfile

- examples/ding-dong-bot.go
examples maintain
1. fix example imports
2. start service with using DaemonStart() instead of Start()
3. correct if conditions return in OnMessage handler
4. correct code fragment of replying image
5. add code fragment of replying url link
> fix: examples maintain

- go.mod
- wechaty-puppet-service/puppet_service.go
- wechaty-puppet/option.go
Support gRpc automatic reconnection
https://github.com/wechaty/go-wechaty/issues/105
> feature: grpc auto reconnect

- wechaty/user/message.go
https://github.com/wechaty/go-wechaty/issues/114
> fix: MentionText()

- wechaty/user/room.go
https://github.com/wechaty/go-wechaty/issues/111
> fix: room.Ready()

- wechaty-puppet-service/puppet_service.go
- wechaty-puppet/puppet.go
- wechaty/user/contact.go
- wechaty/user/room.go
- wechaty/wechaty.go
Using wechaty/wechaty:1.19 will cause an infinite loop, so go-wechaty needs to be adapted.
related: https://github.com/wechaty/wechaty/pull/2380
> Fix deadloop for dirty

- wechaty-puppet-service/puppet_service.go
> fix: compatible old puppet service with mini program

- wechaty/wechaty.go
> fix: on ready

- wechaty/config/config.go
- wechaty/user/message.go
> fix(message): MentionList

- wechaty-puppet-service/helper.go
- wechaty-puppet-service/puppet_service.go
issue: https://github.com/wechaty/go-wechaty/issues/151
> fix: msg date
